### ISSUE TITLE
Problem in installing genetic-pacakge

### ISSUE THREAD

**Issue by widhadyah** [handcraftsman/GeneticAlgorithmsWithPython#1]
Hi, 

I am glad I found your book and think that it could be a big help to my work.
I just started Python and today I found that I need to install genetic-package while running through your book's pages.
I am using Python 3.5 and PyCharm IDE, and trying to install the package with pip ( pip install genetic ) but got this error:

```
Collecting genetic
  Using cached genetic-0.1.dev3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Widha\AppData\Local\Temp\pycharm-packaging\genetic\setup.py", line 39, in <module>
        packages=find_packages("./"),
      File "C:\Python35\lib\site-packages\setuptools\__init__.py", line 58, in find
        convert_path(where),
      File "C:\Python35\lib\distutils\util.py", line 127, in convert_path
        raise ValueError("path '%s' cannot end with '/'" % pathname)
    ValueError: path './' cannot end with '/'
```

How can I fix this? I have no problem installing other packages so far.

Thank you in advance,
Widha

**Comment by handcraftsman** [comment]
Widha,

Thanks for contacting me.  You don't download the `genetic` package.  The
book shows you how to build it.

Clinton
