### ISSUE TITLE
Missing "R100_1gb.col" in Ch05

### ISSUE THREAD

**Issue by jasonwirth** [handcraftsman/GeneticAlgorithmsWithPython#6]
The file "R100_1gb.col" is missing. Hence the code/tests don't run. 

```python
def test_R100_1gb(self):
        self.color("R100_1gb.col",
                   ["Red", "Orange", "Yellow", "Green", "Blue", "Indigo"])
```

**Comment by handcraftsman** [comment]
R100_1gb.col is not my file, so I do not include it in my project. However you should be able to get it from https://turing.cs.hbg.psu.edu/txn131/graphcoloring.html or through a Google/Bing search.
